### PR TITLE
Update actions/checkout version

### PR DESCRIPTION
**Pull request by giraffate**
`actions/checkout@v3` is available now: https://github.com/actions/checkout/blob/main/CHANGELOG.md

### CODE REVIEW

**Comment by giraffate** [comment]
The Clippy test fails because the new lint was added in 1.67. I'll prepare a fix for it tomorrow.

**Comment by Keats** [comment]
Yeah I just got the same on another repo. I'm tempted to remove ` -D warnings` since i don't want some clippy warnings are kind of opinionated and don't have a notion of MSRV

**Comment by giraffate** [comment]
Clippy can support the MSRV by setting the msrv tag in clippy.toml. Does this project have that version? I can't find it.

**Comment by giraffate** [comment]
> Clippy can support the MSRV by setting the msrv tag in clippy.toml. Does this project have that version? I can't find it.

I missed it in README. And I set `rust-version` in Cargo.toml instead of adding clippy.toml.

**Review by Keats — APPROVED** [review]

**Pull request merged**
