### PR TITLE
Release

### PR DESCRIPTION
**Pull request by Keats**

### CODE REVIEW

**Comment by Keats** [comment]
I'll remove the CI and work on wasm support in another release

**Comment by lpotthast** [comment]
@Keats This commit alone d4f3300960efa0da65fd6533bc3e2dc8f573565b would be enough for me to work on an and release a "working" 0.1 release of https://github.com/lpotthast/leptos-keycloak-auth. In its current state, this library would only be usable with a git or path dependency, as jsonwebtoken 9.1.0 hat the problem mentioned in your commit. Other that that, jsonwebtoken builds and runs fine for me in wasm! Would appreciate a release which incorporates your commit.
One downside of the `ring` dependecy is the requirement to install certain additional packages to allow non-failing builds, like clang on linux, llvm on mac, ... with confusing error messages if you dont.

**Comment by Keats** [comment]
> Other that that, jsonwebtoken builds and runs fine for me in wasm! 

Can you easily write a GH action CI test? My attempt in the commit in this PR failed but I don't really know anything about wasm tbh. I'll merge it either way, it just would be nice to know if it works reliably for wasm...

**Comment by lpotthast** [comment]
Hey @Keats, gave it a shot at https://github.com/Keats/jsonwebtoken/pull/346. Feel free to change anything. Would be nice if you could change the GitHub action so that all dependencies for the `wasm-pack` call are met (namely, nodejs and wasm-pack being available). Have very little knowledge about GitHub actions and the dtolnay stuff you are using there.

**Comment by Keats** [comment]
Yep i'll add it

**Pull request merged**
