### PR TITLE
v6

### PR DESCRIPTION
**Pull request by Keats**

### CODE REVIEW

**Comment by nayato** [comment]
Would be great to see it through (along with new crate version)

**Comment by neoeinstein** [comment]
A ping on this. It would be nice to get the ring 0.14 dependency change merged in sooner than later.

**Comment by saks** [comment]
Same ask here about the ring 0.14. This really blocks my project from migration to a next version of many other packages.

**Comment by Keats** [comment]
I'll merge and release tomorrow most likely

**Pull request merged**
