### PR TITLE
Made spec_claims exp, nbf, iss, sub, and aud optional, unless they are specifically required

### PR DESCRIPTION
**Pull request by cloutiertyler**

### CODE REVIEW

**Comment by Keats** [comment]
I'm thinking maybe just copying https://github.com/jpadilla/pyjwt/blob/827d4425dbd2e6f9b521e514ced889cfb3aada21/jwt/api_jwt.py#L122 for the logic would be enough, what do you think?

**Comment by cloutiertyler** [comment]
Hard to go wrong with copying another implementation, but I haven't looked to closely at pyjwt. @brocaar does pyjwt have a good implementation?

**Comment by brocaar** [comment]
@cloutiertyler sorry for the delay. I'm not sure how good the Python implementation actually is. I've been using mostly the Go implementation, which worked well for me. I've only looked at the Python implementation as comparison for this issue.

**Comment by Keats** [comment]
I haven't looked at the Go library but I'm guessing it's probably similar?

**Comment by brocaar** [comment]
Yes, I think it is quite similar, see:

https://github.com/golang-jwt/jwt/blob/d489c99d3e8a82bd47dcb3e4880414f7f747eaa7/claims.go#L50

**Comment by brocaar** [comment]
@cloutiertyler I have created #247 which contains your commits + formatting and clippy feedback fixes.

**Comment by xbladesub** [comment]
any updates on this? Why PR was closed?

**Comment by Keats** [comment]
See the commit about the closed message: https://github.com/Keats/jsonwebtoken/pull/247
it has been released

**Pull request closed without merging**
