### PR TITLE
Fix #190 / cleanup of PR #240

### LINKED ISSUE #190: The exp claim should be optional
According to the RFC, the `exp` claim should be optional: https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.4

> 4.1.4.  "exp" (Expiration Time) Claim
> ... Use of this claim is OPTIONAL.

I saw that you suggested that the user just set an expiration very far in the future. This works for new tokens, however it doesn't work for tokens created previously (e.g. if you're migrating tokens to a new service).

### PR DESCRIPTION
**Pull request by brocaar**
This PR contains the changes made by @cloutiertyler. The only thing that I have done is ran `cargo fmt` and fixed the feedback provided by `cargo clippy`. This solves issue #190.

### CODE REVIEW

**Comment by cloutiertyler** [comment]
Awesome! Are there any additional tests we should have or do the tests I added look good?

**Comment by Keats** [comment]
I think it's fine! If you both confirmed it works for you, I'll merge and release sometimes this week

**Comment by Keats** [comment]
That should be 8.1 and not 9.0 right?

**Comment by cloutiertyler** [comment]
👏 Thank you!

**Pull request merged**
