### PR TITLE
Add the ability to decode a JWT token without specifying an audience.

### LINKED ISSUE #335: `aud` mismatch rejections are hard to debug
The change made in #332 has makes it hard to figure out what is going wrong when a token is rejected for having the wrong audience. I already check for this in my application code and provide a meaningful error, but without some way to decode the JWT to understand _what `aud` was sent_ I cannot convert my code to utilize this new version without doing manual `base64` + `serde_json` deserialization.

While I agree this change is necessary to match the spec, I'd like to suggest that a similar method to `Validation::insecure_disable_signature_validation` is introduced to aid in inspecting invalid JWTs.

Storing the rejected `aud` in the error type would also work, but I suspect this is less desirable for this crate.

### PR DESCRIPTION
**Pull request by sagunb**
Adding this allows us to continue using this library to decode a JWT token without a secret (the way it used to be possible pre v9).

Without this we cannot update to v9 and we are stuck in v8.3.

closes #335

### CODE REVIEW

**Comment by sagunb** [comment]
This would also help alleviate the issue raised in https://github.com/Keats/jsonwebtoken/issues/335

**Review by Keats — APPROVED** [review]

**Comment by sagunb** [comment]
Can you merge the PR, I can't do it because I don't have write access to the repo.

**Comment by Keats** [comment]
I'll merge it soon, just waiting a bit to maybe group it with some wasm stuff

**Comment by horacimacias** [comment]
I'm also interested in this. If there is anything I can help to make this PR merged please let me know.

**Comment by horacimacias** [comment]
thanks!

**Pull request merged**
