### PR TITLE
fix issue 120: DecodingKey can be converted to static

### PR DESCRIPTION
**Pull request by Hexilee**
I ran into #120 as well, so did a little changes.

### CODE REVIEW

**Comment by Keats** [comment]
Thanks for that!
Can we remove the changes to 'static for now as it is a breaking change and only have the CoW + into_static? That would make it easier to use without a breaking change I think?

**Comment by Hexilee** [comment]
Of course, I reverted it now.

**Comment by Hexilee** [comment]
Excuse me, but, can we merge this PR and publish a new version as soon as possible? I really need it.

**Comment by Keats** [comment]
@MayaWolf and @tjwilson90 would this PR work for you?

**Comment by tjwilson90** [comment]
Yes, this looks good.

**Comment by MayaWolf** [comment]
I went for a different approach in [my fork](https://github.com/MayaWolf/jsonwebtoken/commit/025ddc2f6cfc60dfa4df4ff15669fe7c4e0c8f39), where the DecodingKey and EncodingKey construction methods consume/move their parameters, which I think is the most versatile option - but that would be a breaking change, so if you're interested it's probably better to hold off until a major version bump.

**Comment by Keats** [comment]
I think I prefer the approach of @Hexilee on that, making things Cow instead of owned so we don't **need** to clone when we can avoid it. That will be a change for the next version whenever it happens.

**Pull request merged**
